apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: primeiro-pod
  ports:
    - name: http
      port: 443
      targetPort: 80
      nodePort: 31000
      protocol: TCP
